# Generated by Django 5.0.6 on 2026-06-17 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='tracking_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
