# Generated by Django 5.0.6 on 2026-06-17 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_features_product_suitable_for_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('monitors', 'أجهزة قياس صحية'), ('vitamins', 'فيتامينات ومكملات'), ('first_aid', 'إسعافات أولية'), ('orthopedics', 'دعامات وعظام'), ('personal_care', 'عناية شخصية'), ('dental', 'عناية بالأسنان')], default='personal_care', max_length=50),
        ),
    ]
